'use strict';
// trigger: main.command.watch.eventness.tests expected-red native behavior, explicitly selected
const test=require('node:test');
const {fs,path,assert,WATCH,WARP,TOPIC,fixture,invoke,success,create,subscribe,drain,notifications,publish,snapshot}=require('./main.command.watch.eventness.helpers.cjs');
function setup(t){const root=fixture(t);create(root);subscribe(root);return root;}
test('registration: durable subscription does not mutate producer artifacts or launch dispatch',t=>{const root=fixture(t);const before=snapshot(root);create(root);subscribe(root);const after=snapshot(root);for(const [name,bytes] of Object.entries(before))assert.equal(after[name],bytes);assert.ok(Object.keys(after).some(n=>n.includes('watch')));assert.ok(!Object.keys(after).some(n=>n.includes('dispatch')));});
test('minimal: a producer declaration needs no Warp, attempt or revision metadata',t=>{const root=setup(t);const id='demo.watch.eventness.minimal.ready';fs.writeFileSync(path.join(root,'eventness','minimal.txt'),`publish: ${id}\nA small useful result.\n`);assert.deepEqual(notifications(drain(root)),[id]);});
test('project-scope: a topic needs no Warp map when --warp is omitted',t=>{const root=fixture(t);fs.unlinkSync(path.join(root,'warps',WARP+'.warp-map.json'));success(invoke(WATCH,root,['topic','create',TOPIC,'--filter',WARP+'.**.ready','--eventness-dir','eventness','--confirm']));subscribe(root);const id=WARP+'.minimal.ready';fs.writeFileSync(path.join(root,'eventness','minimal.txt'),`publish: ${id}\nProject result.\n`);assert.deepEqual(notifications(drain(root)),[id]);});
test('single: persisted intelligence is announced only by trace ID',t=>{const root=setup(t),p=publish(root);assert.deepEqual(notifications(drain(root)),[p.id]);assert.ok(fs.readFileSync(p.file,'utf8').includes('Useful persisted intelligence'));});
test('multiple-empty: two signatures resolve rich files and an empty referenced marker',t=>{const root=setup(t);fs.writeFileSync(path.join(root,'eventness','empty.marker'),'');const a=publish(root,'alpha',{refs:['eventness/empty.marker']}),b=publish(root,'beta');assert.deepEqual(notifications(drain(root)).sort(),[a.id,b.id].sort());assert.equal(fs.statSync(path.join(root,'eventness','empty.marker')).size,0);});
test('deduplicate-restart: separate processes retain cursor and repeated registration does not reset it',t=>{const root=setup(t),p=publish(root);assert.deepEqual(notifications(drain(root)),[p.id]);subscribe(root);assert.deepEqual(notifications(drain(root)),[]);});
test('missed-wakeup: subscribe and later drain recover publications without an active listener',t=>{const root=fixture(t);create(root);const p=publish(root);subscribe(root);assert.deepEqual(notifications(drain(root)),[p.id]);});
test('foreign-warp: matching trace pattern cannot bypass Warp identity',t=>{const root=setup(t);publish(root,'foreign',{warp:'demo.foreign',uuid:'01a11724-8143-7837-85b1-5a94bc2a2c0e'});const p=publish(root);assert.deepEqual(notifications(drain(root)),[p.id]);});
test('new-revision: a later immutable artifact under the same signature wakes again',t=>{const root=setup(t),p=publish(root);assert.deepEqual(notifications(drain(root)),[p.id]);publish(root,'alpha',{revision:2,body:'Revised persisted result'});assert.deepEqual(notifications(drain(root)),[p.id]);assert.deepEqual(notifications(drain(root)),[]);});
test('missing-reference: unsuccessful drain cannot acknowledge an incomplete publication',t=>{const root=setup(t),p=publish(root,'alpha',{refs:['eventness/not-yet-present.txt']});const failed=drain(root);assert.notEqual(failed.status,0);assert.ok(!failed.stdout.trim()||JSON.parse(failed.stdout).length===0);fs.writeFileSync(path.join(root,'eventness/not-yet-present.txt'),'Published attachment');assert.deepEqual(notifications(drain(root)),[p.id]);});
test('reference-escape: out-of-root attachment cannot signal successful publication',t=>{const root=setup(t);publish(root,'alpha',{refs:['../outside.txt']});const failed=drain(root);assert.notEqual(failed.status,0);assert.ok(!failed.stdout.trim()||JSON.parse(failed.stdout).length===0);});
